### ISSUE TITLE
Installing sshkernel breaks pip3

### ISSUE THREAD

**Issue by SteveWaggoner** [NII-cloud-operation/sshkernel#30]
Trying to install the `sshkernel` library seems to fail because a `pexpect` requirement that isn't met. But then install process breaks `pip` by messing up the open ssl libraries. Once pip is broken its impossible to fix the open ssl libraries.

```
ubuntu@ip-172-31-7-71:~$ pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

ubuntu@ip-172-31-7-71:~$ sudo pip3 install -U sshkernel
Collecting sshkernel
  Downloading sshkernel-0.11.1-py3-none-any.whl (11 kB)
Collecting plumbum
  Downloading plumbum-1.8.3-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 16.9 MB/s
Collecting ipython>=7.0.0
  Downloading ipython-8.12.3-py3-none-any.whl (798 kB)
     |████████████████████████████████| 798 kB 8.2 MB/s
Requirement already satisfied, skipping upgrade: PyYAML in /usr/lib/python3/dist-packages (from sshkernel) (5.3.1)
Collecting nbconvert>=5.4.1
  Downloading nbconvert-7.16.4-py3-none-any.whl (257 kB)
     |████████████████████████████████| 257 kB 63.1 MB/s
Collecting ipykernel>=5.0.0
  Downloading ipykernel-6.29.4-py3-none-any.whl (117 kB)
     |████████████████████████████████| 117 kB 63.2 MB/s
Collecting jupyter-client>=5.2.0
  Downloading jupyter_client-8.6.1-py3-none-any.whl (105 kB)
     |████████████████████████████████| 105 kB 56.7 MB/s
Collecting paramiko>=2.4.2
  Downloading paramiko-3.4.0-py3-none-any.whl (225 kB)
     |████████████████████████████████| 225 kB 55.4 MB/s
Collecting metakernel>=0.20.0
  Downloading metakernel-0.30.2-py3-none-any.whl (217 kB)
     |████████████████████████████████| 217 kB 13.6 MB/s
Requirement already satisfied, skipping upgrade: pexpect>4.3; sys_platform != "win32" in /usr/lib/python3/dist-packages (from ipython>=7.0.0->sshkernel) (4.6.0)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30
  Downloading prompt_toolkit-3.0.43-py3-none-any.whl (386 kB)
     |████████████████████████████████| 386 kB 48.8 MB/s
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting stack-data
  Downloading stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting traitlets>=5
  Downloading traitlets-5.14.3-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 2.6 MB/s
Collecting matplotlib-inline
  Downloading matplotlib_inline-0.1.7-py3-none-any.whl (9.9 kB)
Collecting pygments>=2.4.0
  Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 7.4 MB/s
Collecting typing-extensions; python_version < "3.10"
  Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting jedi>=0.16
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 33.5 MB/s
Collecting jupyter-core>=4.7
  Downloading jupyter_core-5.7.2-py3-none-any.whl (28 kB)
Collecting importlib-metadata>=3.6; python_version < "3.10"
  Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Collecting tinycss2
  Downloading tinycss2-1.3.0-py3-none-any.whl (22 kB)
Collecting nbformat>=5.7
  Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 8.3 MB/s
Collecting markupsafe>=2.0
  Downloading MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Collecting bleach!=5.0.0
  Downloading bleach-6.1.0-py3-none-any.whl (162 kB)
     |████████████████████████████████| 162 kB 59.5 MB/s
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 23.4 MB/s
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Collecting packaging
  Downloading packaging-24.0-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.1 MB/s
Collecting jinja2>=3.0
  Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 66.2 MB/s
Collecting nbclient>=0.5.0
  Downloading nbclient-0.10.0-py3-none-any.whl (25 kB)
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting mistune<4,>=2.0.3
  Downloading mistune-3.0.2-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 6.9 MB/s
Collecting pyzmq>=24
  Downloading pyzmq-26.0.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (912 kB)
     |████████████████████████████████| 912 kB 11.4 MB/s
Collecting debugpy>=1.6.5
  Downloading debugpy-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 18.2 MB/s
Collecting nest-asyncio
  Downloading nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
Collecting comm>=0.1.1
  Downloading comm-0.2.2-py3-none-any.whl (7.2 kB)
Collecting tornado>=6.1
  Downloading tornado-6.4-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
     |████████████████████████████████| 435 kB 57.7 MB/s
Collecting psutil
  Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
     |████████████████████████████████| 288 kB 12.3 MB/s
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     |████████████████████████████████| 229 kB 40.5 MB/s
Collecting pynacl>=1.5
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
     |████████████████████████████████| 856 kB 40.3 MB/s
Collecting bcrypt>=3.2
  Downloading bcrypt-4.1.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (283 kB)
     |████████████████████████████████| 283 kB 62.0 MB/s
Collecting cryptography>=3.3
  Downloading cryptography-42.0.7-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 15.0 MB/s
Collecting wcwidth
  Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Downloading executing-2.0.1-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Downloading asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Collecting parso<0.9.0,>=0.8.3
  Downloading parso-0.8.4-py2.py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 7.6 MB/s
Collecting platformdirs>=2.5
  Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=3.6; python_version < "3.10"->nbconvert>=5.4.1->sshkernel) (1.0.0)
Collecting webencodings>=0.4
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied, skipping upgrade: jsonschema>=2.6 in /usr/lib/python3/dist-packages (from nbformat>=5.7->nbconvert>=5.4.1->sshkernel) (3.2.0)
Collecting fastjsonschema>=2.15
  Downloading fastjsonschema-2.19.1-py3-none-any.whl (23 kB)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/lib/python3/dist-packages (from bleach!=5.0.0->nbconvert>=5.4.1->sshkernel) (1.14.0)
Collecting soupsieve>1.2
  Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Collecting cffi>=1.4.1
  Downloading cffi-1.16.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (444 kB)
     |████████████████████████████████| 444 kB 50.9 MB/s
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     |████████████████████████████████| 117 kB 54.8 MB/s
ERROR: metakernel 0.30.2 has requirement pexpect>=4.8, but you'll have pexpect 4.6.0 which is incompatible.
Installing collected packages: plumbum, wcwidth, prompt-toolkit, backcall, decorator, pickleshare, pure-eval, executing, asttokens, stack-data, traitlets, matplotlib-inline, pygments, typing-extensions, parso, jedi, ipython, platformdirs, jupyter-core, importlib-metadata, webencodings, tinycss2, fastjsonschema, nbformat, markupsafe, jupyterlab-pygments, bleach, soupsieve, beautifulsoup4, pandocfilters, packaging, jinja2, pyzmq, tornado, python-dateutil, jupyter-client, nbclient, defusedxml, mistune, nbconvert, debugpy, nest-asyncio, comm, psutil, ipykernel, pycparser, cffi, pynacl, bcrypt, cryptography, paramiko, metakernel, sshkernel
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 1.5.0
    Not uninstalling importlib-metadata at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'importlib-metadata'. No files were found to uninstall.
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 1.1.0
    Not uninstalling markupsafe at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'MarkupSafe'. No files were found to uninstall.
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 2.10.1
    Not uninstalling jinja2 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Jinja2'. No files were found to uninstall.
  Attempting uninstall: pynacl
    Found existing installation: PyNaCl 1.3.0
    Not uninstalling pynacl at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'PyNaCl'. No files were found to uninstall.
  Attempting uninstall: cryptography
    Found existing installation: cryptography 2.8
    Not uninstalling cryptography at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'cryptography'. No files were found to uninstall.
Successfully installed asttokens-2.4.1 backcall-0.2.0 bcrypt-4.1.3 beautifulsoup4-4.12.3 bleach-6.1.0 cffi-1.16.0 comm-0.2.2 cryptography-42.0.7 debugpy-1.8.1 decorator-5.1.1 defusedxml-0.7.1 executing-2.0.1 fastjsonschema-2.19.1 importlib-metadata-7.1.0 ipykernel-6.29.4 ipython-8.12.3 jedi-0.19.1 jinja2-3.1.4 jupyter-client-8.6.1 jupyter-core-5.7.2 jupyterlab-pygments-0.3.0 markupsafe-2.1.5 matplotlib-inline-0.1.7 metakernel-0.30.2 mistune-3.0.2 nbclient-0.10.0 nbconvert-7.16.4 nbformat-5.10.4 nest-asyncio-1.6.0 packaging-24.0 pandocfilters-1.5.1 paramiko-3.4.0 parso-0.8.4 pickleshare-0.7.5 platformdirs-4.2.2 plumbum-1.8.3 prompt-toolkit-3.0.43 psutil-5.9.8 pure-eval-0.2.2 pycparser-2.22 pygments-2.18.0 pynacl-1.5.0 python-dateutil-2.9.0.post0 pyzmq-26.0.3 soupsieve-2.5 sshkernel-0.11.1 stack-data-0.6.3 tinycss2-1.3.0 tornado-6.4 traitlets-5.14.3 typing-extensions-4.11.0 wcwidth-0.2.13 webencodings-0.5.1

ubuntu@ip-172-31-7-71:~$ pip3 --version
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1571, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1571, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1571, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
ubuntu@ip-172-31-7-71:~$

**Comment by m-ueno** [comment]
@SteveWaggoner  Thank you for reporting the issue. We will investigate it.
